---

- name: Run needed tasks to create datagateway image.
  hosts: 127.0.0.1
  connection: local
  gather_facts: no

  tasks:
  - name: Run task= timezone.
    include_tasks: ./timezone.yml
    vars:
      timezone: "Europe/Vienna"
#    
#    
#    with_items:
#      - "{{  }}"
#
#  - name: Install standard packages - git, ansible.
#    apt:
#      name:
#        - git
#        - ansible
#      state: latest
#      update_cache: true
#
#  - name: Install ansible packages.
